### ISSUE TITLE
Incorrect time of cropped activities

### ISSUE THREAD

**Issue by arvemoen** [veloek/tevling#20] opened 2024-03-22 16:02 UTC
Cropped activities in Strava show the wrong time (and probably distance) in Tevling

Strava:
<img width="851" alt="Strava" src="https://github.com/veloek/tevling/assets/86374497/cd1893b4-d80a-4713-9f3b-12156dbe0fa4">

Tevling:
<img width="541" alt="Tevling" src="https://github.com/veloek/tevling/assets/86374497/827f5a45-ea59-49fb-ab11-3336313bc202">

**Comment by veloek** [comment] 2024-04-14 20:32
I managed to reproduce this issue now and the problem is that Strava is not sending an update event after cropping an activity so Tevling isn't aware of the update.

I'll check to see if this can be improved from their side, but for now the workaround is to manually update the activity in Strava (change title, description, etc.) to trigger an update event in Tevling, after which the activity details will be correct.

Closing this as it cannot be fixed on our side.

**Closed by veloek** 2024-04-14 20:32 UTC
Labels: bug

**Comment by veloek** [comment] 2024-05-23 06:29
I've re-read the documentation regarding webhook events and it's stated that only changes to title, type or privacy will trigger an update event, which explains this issue.

This means that you have to modify the title of the activity while editing other properties for Tevling to receive an update. It sucks, but I don't see an easy workaround for it... We could consider updating activities with a timer an hour or a day after it was created in a best effort to catch changes, but that would multiply the number of requests we do against the Strava API for which we have a quota.
